# Generated by Django 2.1.1 on 2018-10-30 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepermission',
            old_name='Permission',
            new_name='permission',
        ),
    ]
